### Site metadata ###

site_name: ninjinrock
site_description: ninjinrock on GH Pages - including CI
site_url: https://yKanekiti.github.io/ninjinrock/

repo_url: https://github.com/yKanekiti/ninjinrock/
edit_uri: edit/main/docs/docs

### Build settings ###

theme:
  name: material
  language: ja
  palette:
    primary: red
  features:
    - navigation.tabs

markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True

nav:
  - HOME: index.md
  - CONTENTS:
    - メイン: dir1/page1-1.md
    - 確率分布: 
      - いろいろな分布: dir1/page1-2.md
      - 期待値と分散の証明: dir1/page1-2-proof.md